### ISSUE TITLE
`ta init` fails to taken in arguments 

### ISSUE THREAD

**Issue by anthonywong555** [twilio/autopilot-cli#23] opened 2019-08-15 15:33 UTC
When I try to execute the following command:

`ta init --account <account-sid> --token <auth-token>`

I'm still being asked to re-enter the <account-sid> and <auth-token>. 

When I try to re-execute the same command, but with the --credentials flag: 

`ta init --account <account-sid> --token <auth-token> --credentials <name>`

I get the following error back:

`TypeError: Cannot read property 'trim' of undefined
    at twillioInitProfile (/usr/local/lib/node_modules/@twilio/autopilot-cli/lib/twilio-assistant/initConfig.js:50:47)
    at Object.initConfig (/usr/local/lib/node_modules/@twilio/autopilot-cli/lib/twilio-assistant/initConfig.js:16:13)`

**Comment by tingiris** [comment] 2019-09-26 13:07
Hi, @fireredlink5000. I have not been able to reproduce this error but we've made some updates to the init code. Can you please try this again and let me know if the issue still exists? Thanks!

**Comment by pranavdesh** [comment] 2019-09-26 21:17
Hey @tingiris , here are the steps to reproduce:
1. Try and create a new set of credentials with ta init --account <account-sid> --token <auth-token> . The CLI ignores the arguments and asks you to enter the sid and token again. It should only ask you to enter the name of your credentials since you've already provided the sid and token.
2. When you execute this command with --credentials added, it should just create the credentials for you. Right now this throws a TypeError.

**Comment by pranavdesh** [comment] 2019-10-10 21:55
Fixed in version 0.0.27

**Closed as completed by pranavdesh** 2019-10-10 21:55 UTC
